version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /
    schedule:
      interval: daily
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directories:
      - /
    schedule:
      interval: daily
    open-pull-requests-limit: 5
