type: object
properties:
  services:
    anyOf:
      - type: "null"
      - type: object
        propertyNames: { type: string, format: kebab-case }
        minProperties: 1
        additionalProperties:
          anyOf:
            - type: "null"
            - type: object
              properties:
                components:
                  anyOf:
                    - type: "null"
                    - type: object
                      propertyNames: { type: string, format: camel-case-strict }
                      minProperties: 1
                      additionalProperties: { type: object }

                config: { type: object }

              minProperties: 1
              additionalProperties: false

  defaultService: { type: ["null", string] }

  components:
    anyOf:
      - type: "null"
      - type: object
        propertyNames: { type: string, format: camel-case-strict }
        additionalProperties:
          type: ["null", object]

  config: { type: ["null", object] }

additionalProperties: false
required: []
