type: object
properties:
  usernameIsEmail: { type: boolean }
  newUserEnabled: { type: boolean }
  defaultGravatarEmail: { type string, format: email }
  defaultGravatarImage: { anyOf: [{ type: string, format: url }, { enum: [404, mp, identicon, monsterid, wavatar, retro, robohash, blank] }] }
  authCacheMaxSize: { type: integer, minimum: 0 }
  authCacheLastActivityDropInterval: { type: integer, minimum: 10_000 } # ms
  sessionMaxAge: { type: integer, minimum: 60_000 } # ms
  tokenMaxAge: { type: integer, minimum: 60_000 } # ms
  objectUserCacheMaxSize: { type: integer, minimum: 0 }
  apiCallLogCacheDropInterval: { type: integer, minimum: 10_000 } # ms
  defaultGravatarUrl: { type: string, format: url }

  apiEnabled: { type: boolean }
  rpcEnabled: { type: boolean }
  privateHttpServerEnabled: { type: ["null", boolean] }
  publicHttpServerEnabled: { type: ["null", boolean] }

  apiMaxPayloadLength: { type: integer, minimum: 1 }
  apiIdleTimeout: { type: integer, minimum: 0 }
  apiSendPingsAutomatically: { type: boolean }
  apiCompression: { type: boolean }
  rpcMaxPayloadLength: { type: integer, minimum: 1 }
  rpcIdleTimeout: { type: integer, minimum: 0 }
  rpcSendPingsAutomatically: { type: boolean }
  rpcCompression: { type: boolean }

  permissions:
    type: object
    additionalProperties:
      type: object
      properties:
        name: { type: string }
        description: { type: string }
        default: { type: boolean }
      required: [name, description, default]
      additionalProperties: false

  objects:
    type: object
    additionalProperties:
      type: object
      properties:
        id: { type: integer, minimum: 0 }
        roles:
          type: object
          additionalProperties:
            type: object
            properties:
              name: { type: string }
              description: { type: string }
              canEditRoles: { type: boolean }
            required: [name, description]
            additionalProperties: false
      # required: [id, roles]

  notifications:
    type: object
    additionalProperties:
      type: object
      properties:
        name: { type: string }
        description: { type: string }
        channels:
          type: object
          properties:
            internal: { type: boolean }
            email: { type: boolean }
            telegram: { type: boolean }
            push: { type: boolean }
          required: [internal, email, telegram, push]
          additionalProperties: false
      required: [name, description, channels]
      additionalProperties: false

required:
  - usernameIsEmail
  - newUserEnabled
  - defaultGravatarEmail
  - defaultGravatarImage
  - authCacheMaxSize
  - authCacheLastActivityDropInterval
  - tokenMaxAge
  - objectUserCacheMaxSize
  - apiCallLogCacheDropInterval
  - defaultGravatarUrl

  - apiEnabled
  - rpcEnabled

  - apiMaxPayloadLength
  - apiIdleTimeout
  - apiSendPingsAutomatically
  - apiCompression
  - rpcMaxPayloadLength
  - rpcIdleTimeout
  - rpcSendPingsAutomatically
  - rpcCompression
