name: core
siteURL:
generateReadme: true
changelog: true
aliases:

logo: # XXX boolean, if true - favicon -> logo.png

# api:
#   lib/api:
#     target: api
#     options:
#       type: "API"

#   lib/rpc:
#     target: rpc
#     options:
#       type: "RPC"
